# Generated by Django 4.2.27 on 2025-12-07 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
        ('document_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='library_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='library_app.document'),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document_analyses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
