"""
Django settings for sanad_system project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Import environment variables
from decouple import config, Csv
import os

# SECURITY WARNING: keep the secret key used in production secret!
import secrets as _secrets
SECRET_KEY = config('SECRET_KEY', default='django-insecure-' + _secrets.token_hex(40))

# SECURITY WARNING: don't run with debug turned on in production!
# Default False; set DEBUG=True via env var only in development.
DEBUG = config('DEBUG', default=False, cast=bool)

# Raise loudly if running in production with the insecure default key
from django.core.exceptions import ImproperlyConfigured as _ImproperlyConfigured
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise _ImproperlyConfigured(
        "SECRET_KEY must be explicitly set via the SECRET_KEY environment variable in production."
    )

# ALLOWED_HOSTS — restrict in production; safe defaults for local dev
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_jalali',
    'crispy_forms',
    'crispy_bootstrap5',
    'hadith_app',
    'library_app',
    'sslserver',
    'rest_framework',
    'django_celery_results',
    'document_analysis',
    'rag_app',
]

# Optional security app
try:
    import axes  # noqa: F401
    INSTALLED_APPS.append('axes')
except ImportError:
    pass

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For language detection
    'hadith_app.middleware.ForceDefaultLanguageMiddleware',  # Force Arabic language
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
]

# Optional security middleware
try:
    import axes  # noqa: F401
    MIDDLEWARE.insert(8, 'axes.middleware.AxesMiddleware')
except ImportError:
    pass

ROOT_URLCONF = 'sanad_system.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'hadith_app/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hadith_app.context_processors.theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanad_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('PGDATABASE', os.environ.get('DB_NAME', 'sanad')),
        'USER': os.environ.get('PGUSER', os.environ.get('DB_USER', 'postgres')),
        'PASSWORD': os.environ.get('PGPASSWORD', os.environ.get('DB_PASSWORD', 'postgres')),
        'HOST': os.environ.get('PGHOST', os.environ.get('DB_HOST', 'localhost')),
        'PORT': os.environ.get('PGPORT', os.environ.get('DB_PORT', '5432')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Arabic language settings
LANGUAGE_CODE = 'ar'
LANGUAGES = [
    ('ar', ('العربية')),
]

# RTL languages
LANGUAGES_BIDI = ["ar"]

# Time and date settings
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Locale paths
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Format localization
FORMAT_MODULE_PATH = [
    'sanad_system.formats',
]

# First day of week (0=Sunday, 1=Monday, 6=Saturday)
FIRST_DAY_OF_WEEK = 6  # Saturday

# Date formats
DATE_FORMAT = 'Y/m/d'
DATETIME_FORMAT = 'Y/m/d H:i'
TIME_FORMAT = 'H:i'

# Number formats
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Ensure the media directory exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# PDF Reader Settings
PDF_UPLOAD_DIR = os.path.join(MEDIA_ROOT, 'pdf_uploads')
os.makedirs(PDF_UPLOAD_DIR, exist_ok=True)

# Security settings
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
X_FRAME_OPTIONS = 'SAMEORIGIN'
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Axes brute-force protection (optional)
try:
    import axes  # noqa: F401
    AXES_FAILURE_LIMIT = 5
    AXES_COOLOFF_TIME = 1  # hours
    AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
    AXES_RESET_ON_SUCCESS = True
except ImportError:
    pass

# CSRF trusted origins for Replit proxy
CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
    'https://*.replit.app',
    'http://localhost:5000',
    'http://0.0.0.0:5000',
]

# Message tags for Bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production settings - uncomment for production
# DEBUG = False  # Only set to False in production
# ALLOWED_HOSTS = ['your-domain.com']  # Specify actual domains in production

# Custom error handlers are now defined in urls.py

# Authentication settings
LOGIN_REDIRECT_URL = 'hadith_app:hadith_list'  # Redirect after login
LOGOUT_REDIRECT_URL = 'hadith_app:hadith_list'  # Redirect after logout
LOGIN_URL = 'login'  # URL to redirect to for login

# Session settings
SESSION_COOKIE_AGE = 86400  # 1 day in seconds
SESSION_SAVE_EVERY_REQUEST = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'library': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'hadith_processor': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='filesystem://')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Riyadh'

if not DEBUG and CELERY_BROKER_URL in ('memory://', 'filesystem://'):
    raise ImproperlyConfigured(
        "CELERY_BROKER_URL must be explicitly set via environment variable in production."
    )
