# Generated by Django 5.2 on 2025-06-30 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(max_length=100, verbose_name='المؤلف')),
                ('year_written', models.IntegerField(blank=True, null=True, verbose_name='سنة التأليف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'كتاب الحديث',
                'verbose_name_plural': 'كتب الحديث',
            },
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الراوي')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الميلاد')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الوفاة')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='السيرة الذاتية')),
                ('reliability', models.CharField(choices=[('thiqa', 'ثقة'), ('saduq', 'صدوق'), ('weak', 'ضعيف'), ('unknown', 'مجهول')], max_length=20, verbose_name='درجة التوثيق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'راوي',
                'verbose_name_plural': 'الرواة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HadithCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hadith_app.hadithcategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف الحديث',
                'verbose_name_plural': 'تصنيفات الأحاديث',
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الحديث')),
                ('source', models.CharField(max_length=200, verbose_name='المصدر')),
                ('source_page', models.CharField(blank=True, max_length=50, null=True, verbose_name='الصفحة')),
                ('source_hadith_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحديث في المصدر')),
                ('grade', models.CharField(blank=True, choices=[('sahih', 'صحيح'), ('hasan', 'حسن'), ('daif', 'ضعيف'), ('mawdu', 'موضوع')], max_length=20, null=True, verbose_name='درجة الحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='hadith_app.hadithcategory', verbose_name='التصنيفات')),
            ],
            options={
                'verbose_name': 'حديث',
                'verbose_name_plural': 'الأحاديث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mutawatir', models.BooleanField(default=False, verbose_name='متواتر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asanid', to='hadith_app.hadith', verbose_name='الحديث')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'الأسانيد',
                'ordering': ['hadith'],
            },
        ),
        migrations.CreateModel(
            name='SanadNarrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='ترتيب الراوي في السند')),
                ('narration_method', models.CharField(blank=True, help_text='مثل: حدثنا، أخبرنا، عن، أنبأنا', max_length=100, null=True, verbose_name='طريقة الرواية')),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadith_app.narrator', verbose_name='الراوي')),
                ('sanad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadith_app.sanad', verbose_name='السند')),
            ],
            options={
                'verbose_name': 'راوي السند',
                'verbose_name_plural': 'رواة الأسانيد',
                'ordering': ['sanad', 'order'],
                'unique_together': {('sanad', 'order')},
            },
        ),
        migrations.AddField(
            model_name='sanad',
            name='narrators',
            field=models.ManyToManyField(through='hadith_app.SanadNarrator', to='hadith_app.narrator', verbose_name='الرواة'),
        ),
    ]
