# Generated by Django 5.2 on 2025-07-03 08:31

import django.db.models.deletion
import hadith_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة شخصية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع')),
                ('avatar', models.ImageField(blank=True, help_text='صورة الملف الشخصي', null=True, upload_to=hadith_app.models.user_avatar_path, verbose_name='الصورة الشخصية')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('system', 'تلقائي (حسب النظام)')], default='system', max_length=10, verbose_name='السمة')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب تويتر')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='حساب فيسبوك')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('email_verified', models.BooleanField(default=False, verbose_name='تم التحقق من البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
                'ordering': ['-created_at'],
            },
        ),
    ]
