# Generated by Django 5.2 on 2025-07-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0003_add_profile_to_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='سياق الحديث'),
        ),
        migrations.AddField(
            model_name='hadith',
            name='reference_edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='طبعة المرجع'),
        ),
        migrations.AddField(
            model_name='hadith',
            name='reference_page',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='صفحة المرجع'),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة'),
        ),
    ]
