# Generated by Django 4.2.23 on 2025-07-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0004_hadith_context_hadith_reference_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanadnarrator',
            name='narrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrations', to='hadith_app.narrator', verbose_name='الراوي'),
        ),
    ]
