# Generated by Django 4.2.23 on 2025-07-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hadith_app', '0005_alter_sanadnarrator_narrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='documents/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('text', 'نصي'), ('pdf', 'PDF'), ('word', 'Word'), ('other', 'آخر')], max_length=10, verbose_name='نوع الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل المعالجة')], default='pending', max_length=20, verbose_name='حالة المعالجة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('extracted_hadiths', models.ManyToManyField(blank=True, to='hadith_app.hadith', verbose_name='الأحاديث المستخرجة')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_documents', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
