# Generated by Django 4.2.23 on 2025-07-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
