# Generated by Django 4.2.23 on 2025-07-07 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hadith_app', '0007_remove_document_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hadiths', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة'),
        ),
    ]
