# Generated by Django 4.2.27 on 2025-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0008_alter_hadith_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrator',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الميلاد'),
        ),
        migrations.AddField(
            model_name='narrator',
            name='death_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الوفاة'),
        ),
        migrations.AddField(
            model_name='narrator',
            name='madhhab',
            field=models.CharField(blank=True, choices=[('hanafi', 'حنفي'), ('maliki', 'مالكي'), ('shafi', 'شافعي'), ('hanbali', 'حنبلي'), ('other', 'أخرى'), ('unknown', 'غير معروف')], max_length=50, null=True, verbose_name='المذهب'),
        ),
        migrations.AddField(
            model_name='narrator',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='hadith_app.narrator', verbose_name='الشيوخ'),
        ),
    ]
