# Generated by Django 5.2 on 2025-12-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0009_add_narrator_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='text',
            field=models.TextField(verbose_name='النص الأساسي للحديث'),
        ),
        migrations.CreateModel(
            name='HadithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الحديث')),
                ('source_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='المصدر المحدد')),
                ('narrator_chain', models.TextField(blank=True, null=True, verbose_name='سلسلة الرواة')),
                ('variation_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الاختلاف')),
                ('is_primary', models.BooleanField(default=False, verbose_name='النص الأساسي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='hadith_app.hadith', verbose_name='الحديث')),
            ],
            options={
                'verbose_name': 'نص الحديث',
                'verbose_name_plural': 'نصوص الحديث',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
