# Generated by Django 5.2 on 2025-12-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0010_alter_hadith_text_hadithtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanadText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الحديث')),
                ('source_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='المصدر المحدد')),
                ('variation_notes', models.TextField(blank=True, help_text='أي اختلافات في النص مقارنة بالنسخة الأساسية', null=True, verbose_name='ملاحظات الاختلاف')),
                ('is_primary', models.BooleanField(default=False, help_text='هل هذا هو النص الأساسي للحديث؟', verbose_name='النص الأساسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sanad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanad_text', to='hadith_app.sanad', verbose_name='السند')),
            ],
            options={
                'verbose_name': 'نص السند',
                'verbose_name_plural': 'نصوص الأسانيد',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
