# Generated by Django 5.2 on 2025-12-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0011_sanadtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات حول علاقة التلمذة أو المصادر', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relationships', to='hadith_app.narrator', verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='hadith_app.narrator', verbose_name='الشيخ')),
            ],
            options={
                'verbose_name': 'علاقة تلمذة',
                'verbose_name_plural': 'علاقات التلامذة',
                'ordering': ['teacher__name', 'student__name'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
