# Generated by Django 4.2.27 on 2025-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0012_teacherstudentrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='system_hadith_number',
            field=models.PositiveIntegerField(blank=True, help_text='رقم فريد لكل حديث في النظام', null=True, unique=True, verbose_name='الرقم التسلسلي للحديث'),
        ),
    ]
