# Generated by Django 4.2.27 on 2025-12-13 16:19

from django.db import migrations


def populate_system_hadith_numbers(apps, schema_editor):
    Hadith = apps.get_model('hadith_app', 'Hadith')
    hadiths = Hadith.objects.all().order_by('id')
    for i, hadith in enumerate(hadiths, 1):
        hadith.system_hadith_number = i
        hadith.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0013_hadith_system_hadith_number'),
    ]

    operations = [
        migrations.RunPython(populate_system_hadith_numbers),
    ]
