# Generated by Django 4.2.30 on 2026-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith_app', '0015_enhance_hadith_sanad_narrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrator',
            name='reliability_history',
            field=models.JSONField(blank=True, default=list, verbose_name='سجل التوثيق'),
        ),
    ]
