# Generated by Django 4.2.23 on 2025-07-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pdf_reader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='رابط مخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('file', models.FileField(help_text='الحد الأقصى لحجم الملف 50 ميجابايت', upload_to=pdf_reader.models.document_upload_path, verbose_name='الملف')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='published', max_length=20, verbose_name='الحالة')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الرفع')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='آخر معاينة')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='آخر وصول')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-uploaded_at'],
                'permissions': [('can_share_document', 'يمكنه مشاركة المستندات'), ('can_manage_document', 'يمكنه إدارة المستندات')],
            },
        ),
    ]
