# Generated by Django 4.2.27 on 2025-12-11 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الإعداد')),
                ('embedding_model', models.CharField(max_length=100, verbose_name='نموذج التضمين')),
                ('llm_model', models.CharField(max_length=100, verbose_name='نموذج اللغة')),
                ('chunk_size', models.IntegerField(default=500, verbose_name='حجم الجزء')),
                ('chunk_overlap', models.IntegerField(default=50, verbose_name='تداخل الأجزاء')),
                ('max_context', models.IntegerField(default=5, verbose_name='الحد الأقصى للسياق')),
                ('similarity_threshold', models.FloatField(default=0.7, verbose_name='عتبة التشابه')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات RAG',
                'verbose_name_plural': 'إعدادات RAG',
            },
        ),
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='السؤال')),
                ('response', models.TextField(verbose_name='الإجابة')),
                ('context_used', models.JSONField(default=list, verbose_name='السياق المستخدم')),
                ('embedding_model', models.CharField(default='arabic-embedding', max_length=100, verbose_name='نموذج التضمين')),
                ('llm_model', models.CharField(default='arabic-llm', max_length=100, verbose_name='نموذج اللغة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استعلام RAG',
                'verbose_name_plural': 'استعلامات RAG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('hadith', 'حديث'), ('narrator', 'راوي'), ('book', 'كتاب'), ('category', 'تصنيف')], max_length=20, verbose_name='نوع المحتوى')),
                ('content_id', models.IntegerField(verbose_name='معرف المحتوى')),
                ('text_content', models.TextField(verbose_name='نص المحتوى')),
                ('embedding_vector', models.JSONField(verbose_name='متجه التضمين')),
                ('embedding_model', models.CharField(default='arabic-embedding', max_length=100, verbose_name='نموذج التضمين')),
                ('metadata', models.JSONField(default=dict, verbose_name='البيانات الوصفية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تضمين المستند',
                'verbose_name_plural': 'تضمينات المستندات',
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='rag_app_doc_content_6b3485_idx')],
                'unique_together': {('content_type', 'content_id', 'embedding_model')},
            },
        ),
    ]
